### PR TITLE
adding text via a Pull Request that you can merge

### PR DESCRIPTION
**Pull request by manualwise**
@lilliclark here's a PR that you can read through and then merge. If you merge it, it will be the new version that is live on your repository!

### CODE REVIEW

**Comment by ethangj** [comment]
This is a bad pull request, do not approve it.

**Comment by lilliclark** [comment]
Overruling the king. Merging!  XD @ethangj @manualwise

**Comment by rknotek** [comment]
Looks good to me :)

**Comment by moritzplassnig** [comment]
Sad

**Pull request merged**
